[build]
  command = "npm run build"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--include=dev"

[[redirects]]
  from = "/favicon.ico"
  to = "/beartankLogo1.png"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
